export const battingStatsMapping = {
    team: "Equipo",
    league: "Liga",
    G: "Juegos jugados",
    AB: "Turnos al bat",
    R: "Carreras",
    H: "Hits",
    "2B": "Dobles",
    "3B": "Triples",
    HR: "Home runs",
    RBI: "Carreras impulsadas",
    BB: "Bases por bolas",
    SO: "Strikeouts",
    SB: "Bases robadas",
    CS: "Outs robando bases",
    AVG: "Porcentaje de bateo",
    OBP: "Porcentaje de embasarse",
    SLG: "Slugging",
    OPS: "Embasado + slugging"
}

export const pitchingStatsMapping = {
    "team": "Equipo",
    "league": "Liga",
    W: 'Juegos ganados',
    L: 'Juego perdidos',
    ERA: 'Porcentaje de carreras permitidas',
    G: 'Juegos',
    GS: 'Juegos iniciados',
    CG: 'Juegos sin relevo',
    SHO: 'Juegos sin permitir carreras',
    SV: 'Saves',
    SVO: 'Oportunidades de Save',
    IP: 'Entradas',
    H: 'Hits',
    R: 'Carreras totales',
    ER: 'Carreras permitidas',
    HR: 'Home runs',
    HB: 'Hits al bateador',
    BB: 'Bases por bolas',
    SO: 'Strikeouts',
    WHIP: 'Bases por bolas y hits por entrada',
    AVG: 'Porcentaje de bateo'
}